CREATE TABLE users
(	
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	username VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE, 
	password VARCHAR(255) NOT NULL UNIQUE,
    creado_el TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

